boston/boston/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    # Hver gang noen går til music på siden lastes music.url filen
    url(r'^music/', include('music.urls')),
]

boston/music/urls.py
from django.conf.urls import url
# from . betyr "hent fra denne mappen", altså . betyr denne mappen.
from . import views
# dette er altså index for music. Hver trenger/bør ha en index

urlpatterns = [
    # ingenting betyr at dette er default for music,
    # /music
    url(r'^$', views.index, name='index'),
    # /music/712/, gruppe () kan se etter *alle* album IDene, så kjører vi det-
    # - inn som variable, regexen kjøre for hvert tall, og sjekker om 0-9
    url(r'^(?P<album_id>[0-9]+)/$', views.detail, name='detail'),
]

boston/music/models.py
from django.db import models

# Create your models here.


class Album(models.Model):
    artist = models.CharField(max_length=250)
    album_title = models.CharField(max_length=500)
    genre = models.CharField(max_length=100)
    album_logo = models.CharField(max_length=1000)

    def __str__(self):
        return self.album_title+' - ' + self.artist


class Song(models.Model):
    album = models.ForeignKey(Album, on_delete=models.CASCADE)
    file_type = models.CharField(max_length=10)
    song_title = models.CharField(max_length=250)

    def __str__(self):
        return self.song_title

boston/music/views.py
from django.http import Http404
from django.shortcuts import render
from .models import Album


def index(request):
    # all albums lagrer albumene fra databasen i en variabel
    all_albums = Album.objects.all()
    return render(request, 'music/index.html', {'all_albums': all_albums})


def detail(request, album_id):
    try:
        album = Album.objects.get(pk=album_id)
    except Album.DoesNotExist: 
        raise Http404("Album not found, it does not exist in our database.")
    return render(request, 'music/detail.html', {'album': album})

boston/music/templates/music/detail.html
<img src="{{ album.album_logo }}"height="320" width="320">

<h1>{{ album.album_title }}</h1>
<h3>{{ album.artist }}</h3>
<ul> 
    {% for song in album.song_set.all %}
    <li> {{song.song_title}} - {{song.file_type}} </li>
    {%endfor%}
</ul>

boston/music/templates/music/index.html
{% if all_albums %}
<h3>Here are all my albums</h3>
<ul>
        {% for album in all_albums %}
        <li><a href="/music/{{ album.id }}/">{{album.id}}  {{  album.album_title }}</a></li>
        {% endfor %}
</ul>
{%else %}
    <h3>You don't have any albums</h3>
{%endif%}